image:
  file: .gitpod.Dockerfile

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: pub get

# Add the DartCode extension. See https://www.gitpod.io/docs/vscode-extensions/
vscode:
  extensions:
    - Dart-Code.dart-code@3.9.0:umvoqCQMs3NpksmwhVtStw==
