name: cassowary
version: 0.3.0+1
description: An implementation of the Cassowary constraint solving algorithm in Dart.
author: Chromium Authors <flutter-dev@googlegroups.com>
homepage: https://github.com/google/cassowary.dart/
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: '^1.5.1+1'
  dart_coveralls: '^0.6.0+4'
  pedantic: '^1.1.0'
  matcher: '^0.12.3+1'
