name: cassowary
version: 0.2.0
description: Cassowary Constraint Solving Toolkit
author: Chromium Authors <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/cassowary
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: ^1.5.1
  dart_coveralls: ^0.6.0+4
